// Generated by CoffeeScript 1.6.3
(function() {
  var _ref, _ref1, _ref2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Raffler = {
    Models: {},
    Collections: {},
    Views: {},
    Routers: {}
  };

  Raffler.Models.Entry = (function(_super) {
    __extends(Entry, _super);

    function Entry() {
      _ref = Entry.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Entry.prototype.defaults = {
      name: null,
      winner: false
    };

    return Entry;

  })(Backbone.Model);

  Raffler.Collections = (function(_super) {
    __extends(Collections, _super);

    function Collections() {
      _ref1 = Collections.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Collections.prototype.model = Raffler.Models.Entry;

    return Collections;

  })(Backbone.Collection);

  Raffler.View = (function(_super) {
    __extends(View, _super);

    function View() {
      _ref2 = View.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    return View;

  })(Backbone.View);

}).call(this);
